### ISSUE TITLE
Could not save new password

### ISSUE THREAD

**Issue by elgs** [yectep/rainloop-mysql-password-change#2]
I kept getting Could not save new password when I attempt to change the password. I didn't see any log on the server.

**Comment by eightyknots** [comment]
Hi @elgs,

If you inspect the network on your browser, what do you get instead of the expected 200 OK response?

**Comment by jacklei** [comment]
@elgs 
I had the same issue when I was setting up. Check your character length limits in your database, specifically for your password hash field.

**Comment by elgs** [comment]
Hi @yectep I actually got 200 OK response. The "Could not save new password" is shown on the web page. I did some more test, if I deliberately make my old password wrong, I get a new error message: Current password incorrect. I further deliberately make the mysql login wrong in the config, I still get exactly the same error message. So base on the facts observed above, I have the following conclusions:
1. The web page cached my old password somewhere. When it says "Current password incorrect", it's based on its cached version of my old password, instead of querying it from the database;
2. Upon my clicking the Set New Password button in the web page, the database is not accessed by the plugin at all, because even if I give wrong mysql login, it didn't complain at all.

Also, I cannot find any log from the logs directory, it's empty. I'm wondering whether my database access module is not working at all. I'm sorry I'm new to PHP, so my questions might be naïve.

**Comment by eightyknots** [comment]
Hi @elgs, during my debugging I have found that if there was an error in your Rainloop config, or database setup, it will still return a 200 OK. In your inspect tab, it may return a JSON object with an error message.

See if you have an error message - if so, feel free to paste it here and I can help out some more.

**Comment by elgs** [comment]
Here is the response JSON, seems to be not interesting.

``` JSON
{"Action":"ChangePassword","Result":false,"ErrorCode":130,"ErrorMessage":"","ErrorMessageAdditional":"","Time":1100}
```

**Comment by eightyknots** [comment]
Do you have error logging enabled in your `application.ini`? Docs on this is available [on the Rainloop site](http://www.rainloop.net/docs/configuration/)

Try turning it on - this should give you more information about your error. It's probably something on your MySQL setup.

```
[logs]
; Enable logging
enable = On
```

**Comment by elgs** [comment]
Thanks @yectep. After enabling logs, it turned out it was a db connection problem. However, when I changed the password, I failed to login with the new password. The new password in my db becomes `$6$rounds=5000$mNZmIcsyghLn/m0p$yc7VNeKI0sjgqaZKPDYaiJjAwnSpnABwWQR25JmDmuyzkMB1CeUDAVqoladH3fLRbstzE6tMnW`. The part `$6$rounds=5000$` looks a little bit suspicious.

**Comment by eightyknots** [comment]
Hi @elgs, `$6$rounds=5000$` is the spec for sha512-crypt hashes. The rounds is equivalent to "cost" in other algorithms, this means it will use the 5000th hash of your salted password.

You should set (in Rainloop admin) the encryption scheme to whatever your mail server is using. If your hashes in the MySQL database of your mail server do not have this prefix, they aren't sha512 hashes.

A `$5$` prefix indicates sha256, `$2y$` is Blowfish (PHP 5.6 and 7's current preferred hash algorithm).

**Comment by elgs** [comment]
I'm using SHA512. But it looks like the way I encrypt the password is not compatible with what the plugin expected. What I did to encrypt the password is like this MySQL expression: `ENCRYPT('my_password', CONCAT('$6$', SUBSTRING(SHA(RAND()), -16)))`.

**Comment by elgs** [comment]
I changed the line to:

``` php
case 'sha512_crypt':
{
    // return crypt($password, '$6$rounds=' . $this->_rounds . '$' . $this->_generateSalt());
    return crypt($password, '$6$' . $this->_generateSalt());
}
```

In my `/etc/dovecot/dovecot-sql.conf.ext`, I have:

`default_pass_scheme = SHA512-CRYPT`

So how can I get dovecot to be aware of the rounds=5000? Thanks.

**Comment by elgs** [comment]
It seems the dovecot documentation doesn't even mention the rounds: http://wiki2.dovecot.org/Authentication/PasswordSchemes. I understand the `rounds` is part of the spec, but how would you get dovecot to recognize the `rounds`?

**Comment by eightyknots** [comment]
Since the rounds are already part of the spec, Dovecot is able to handle the rounds when comparing a password with the stored hash. I am using the same `default_pass_scheme` with no issues with rounds.

Check your MySQL database's password field length. It may be truncating the hash when changing password, and this will cause mismatches when trying to login.

**Comment by elgs** [comment]
My password field is varchar(106), is it too short?

**Comment by elgs** [comment]
@yectep, indeed it's because my password field is too short and the encrypted password got truncated. I changed the length to 500, and it works flawlessly.

By the way, is hash 5000 rounds each time standard practice? I have a lot of email accounts, I was wondering if every login attempt would cause the mail server to have 5000 rounds of hash, is it going to cause significant load to the server, or it is not a problem at all? Thanks.

**Comment by elgs** [comment]
@jacklei thank you. What you reminded was exactly my problem.

**Comment by eightyknots** [comment]
Hi @elgs, without rounds specified the default for libc (and most other implementations) is 5000. I wrote a quick PHP script to test this. Here are the results, in seconds, to `crypt()` a password 1000 times.

If you're currently on "no rounds" specified, then 5000 should be already what the server is doing.

```
Testing no rounds specification
Testing 1000 rounds specification
Testing 5000 rounds specification
Testing 10000 rounds specification
Array
(
    [0] => 5.9692800045013
    [1] => 1.2248229980469
    [2] => 5.9654870033264
    [3] => 12.092165231705
)
```

**Comment by elgs** [comment]
Thank you @yectep! You really taught me something!
